server:
  port: 9103

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/seata-demo-order?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Hongkong
  username: root
  password: 1234

seata:
  enabled: true
  application-id: seata-demo-springboot-order
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      cluster: default
      server-addr: 10.237.145.241:8848,10.237.145.242:8848,10.237.145.243:8848
      namespace: seata